spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/pago_servicios
        username: postgres
        password: olitllvonl102
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect